version: '3.3'
services:
  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_URL=
  #   depends_on:
  #     - db
  db: 
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
